use_frameworks!

workspace 'PZSyncKitCoreData.xcworkspace'
project 'PZSyncKitCoreDataExample/PZSyncKitCoreDataExample'

target 'PZSyncKitCoreDataExample' do
	
  platform :ios, '10.0'

  pod 'PZSyncKit/CoreData', :path => '../../'

  target 'PZSyncKitCoreDataExampleTests' do
    inherit! :search_paths
  end
end

target 'WatchApp' do
	project 'WatchApp/WatchApp'
	platform :watchos, '3.0'
	pod 'PZSyncKit/CoreData', :path => '../../'
end
