use_frameworks!

workspace 'PZSyncKitRealm.xcworkspace'
project 'PZSyncKitRealmExample/PZSyncKitRealmExample'

target 'PZSyncKitRealmExample' do
	
  platform :ios, '10.0'

  pod 'Realm'
  pod 'PZSyncKit/Realm', :path => '../../'

  target 'PZSyncKitRealmExampleTests' do
    inherit! :search_paths
  end
end

target 'PZSyncKitRealmExampleTodayExtension' do

#	project 'PZSyncKitRealmExample'
	platform :ios, '10.0'
	
	pod 'PZSyncKit/Realm', :path => '../../'

	pod 'Realm'
end

post_install do |installer|
     installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
                 config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
           end
     end
 end
