use_frameworks!

workspace 'PZSyncKitRealmSwift.xcworkspace'
project 'PZSyncKitRealmSwiftExample/PZSyncKitRealmSwiftExample'

target 'PZSyncKitRealmSwiftExample' do
	
  platform :ios, '10.0'

  pod 'RealmSwift'
  pod 'PZSyncKit/RealmSwift', :path => '../../'

  target 'PZSyncKitRealmSwiftExampleTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
     installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
                 config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
           end
     end
 end
